theme: jekyll-theme-cayman

title                    : "한창 데이터에 관심 많을 나이"
name                     : "김유노윤호"
description              : "강경 아날로그파의 github 블로그 운영 도전기"
url                      : "https://hjkim9713.github.io"

teaser                   : "/assets/images/bio-photo-keyboard.jpg"
logo                     : # 최상단 메뉴 바에 사이트 로고 넣기
